eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
#    register-with-eureka: false
#    fetch-registry: false
server:
  port: 8763
spring:
  application:
    name: service-mybaties


  datasource:
      #type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
      #driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
      url: jdbc:mysql://120.79.238.232:3306/mldn8001           # 数据库连接地址
      username: root                                  # 数据库用户名
      password: Mytype424...                            # 数据库连接密码
      dbcp2:                                          # 进行数据库连接池的配置
        min-idle: 5                                   # 数据库连接池的最小维持连接数
        initial-size: 5                               # 初始化提供的连接数
        max-total: 5                                  # 最大的连接数
        max-wait-millis: 200                          # 等待连接获取的最大超时时间
      mybatis:
        config-location: classpath:mybatis.xml    # mybatis配置文件所在路径
        type-aliases-package: cn.dxjava.pojo          # 定义所有操作类的别名所在包
        mapper-locations: classpath*:mapper/*.xml      # 所有的mapper映射文件


