eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 7777
  tomcat:
    max-threads: 50    

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000   # 配置访问超时 时间
